### ISSUE TITLE
[HELP] try to access server

### ISSUE THREAD

**Issue by SiscuPrats** [shawly/docker-nut#10]
Hello, 

thank you for this project. I would need some help. I have installed in synology docker this project and I have run it in docker following all the parameters. In principle it does not give any error and is working. I have created the folders and I have put some NSZ to test. 

From browser I get a blank page when I want to access the ip/port after logging in with the user and password guest and from nintendo switch I configure it in tinfoil and it does not load anything at all.

What should I do?

Thanks!

**Comment by erauzkin** [comment]
That error has been fixed here -> https://github.com/blawar/nut/pull/469/files

**Comment by sully316** [comment]
Have same issue, how do I update my docker image with above fix?

**Comment by tschamad** [comment]
Here the same

**Comment by shawly** [comment]
The latest edge image should contain the new fix, you can use the `edge` Tag.
