### ISSUE TITLE
What size should the titledb/.git/objects/pack folder be?

### ISSUE THREAD

**Issue by velvetpants1975** [shawly/docker-nut#11]
Was trouble shooting some cache issues with unRaid and noticed that the files in this location added up to 400gb+.
Is this normal or is something wildly off with my setup?

nut/titledb/.git/objects/pack

**Comment by shawly** [comment]
Yeah that is technically normal as the titledb is updated regularily.
When starting the container the first time, the titledb is cloned with a depth of 1, but every time the container is restarted the titledb will get updated so the git repo will grow in size.

I haven't had considered this yet but over a longer time span the repo can grow huge, I'll see if I can work around that.

**Comment by shawly** [comment]
The new edge image should now keep the size of the titledb repo low. You should delete the titledb folder so the container can clone it again.

**Comment by savaloi** [comment]
Has this (or will this be) incorporated into the main branch? I've just hit this issue today with the same folder being ~180GB while using the main branch.
Thanks
