### ISSUE TITLE
Found files in the titles folder

### ISSUE THREAD

**Issue by Pesoen** [shawly/docker-nut#2]
**Is your feature request related to a problem? Please describe.**
I would like a way to debug if it works correctly on the NUT end, as i can connect to my nut server just fine, but it does not show any of the three nsp files i have in there, all of which work just fine if i load up the nut server on my windows machine.

**Describe the solution you'd like**
a flag you can enable so it will list files in the titles folder that is found, can be some output of NUT or just a check of the files to check it sees the folder correctly.

**Describe alternatives you've considered**
nothing really, other than trying different folders, since the current way is that the folder is actually hosted on my NAS, and is mapped as a local folder so all things should just see it as a folder, not some mysterious black hole.

**Additional context**
nothing really. i think i asked for what i wanted without too many spelling mistakes :P

**Comment by Pesoen** [comment]
got it working, had typed the folder name wrong so it did not see the directory correctly.. would still be a great debugging feature though :)

**Comment by shawly** [comment]
The feature to connect to your container and look at files already comes with Docker (e.g. `docker exec -it <container name or id> /bin/bash` to start a shell to look through files), I don't see much benefit from adding something like this.

**Comment by Pesoen** [comment]
> The feature to connect to your container and look at files already comes with Docker (e.g. `docker exec -it <container name or id> /bin/bash` to start a shell to look through files), I don't see much benefit from adding something like this.

i did not know this. i am still rather new to docker, so thanks for telling me.

**Comment by shawly** [comment]
No worries, I might extend the troubleshooting section in the README.md and add some info about this. Permission and ownership problems are the most common issues people have with Docker. I've had quite a few issues opened in my other https://github.com/shawly/docker-ps3netsrv repo, so it might make sense to add the same troubleshooting steps for this image aswell.
