### ISSUE TITLE
Compatibility report: Raspberry Pi 4B

### ISSUE THREAD

**Issue by Pesoen** [shawly/docker-nut#3]
**Device:**
e.g. Raspberry Pi 1B+
Raspberry Pi 4B 8GB(likely works on lower ram models as well)

**Status:**
[x] works
[ ] not working

**Additional steps to get it to work?**
- none

**Comment by shawly** [comment]
Thanks!

**Comment by Pesoen** [comment]
you are welcome :) just love that my pi now handles my games from a usb hdd, on my nas, to serve it to my switch at any time of the day :P
