### ISSUE TITLE
Update titledb flag is incorrect

### ISSUE THREAD

**Issue by gritstub** [shawly/docker-nut#5]
The script in /var/run/s6/etc/cont-init.d/03-update-titledb is looking for `UPDATE_TITLEDB` instead of `TITLEDB_UPDATE`.

The documentation says that the latter should be correct.

`5: TITLEDB_UPDATE=${UPDATE_TITLEDB:-true}`

**Comment by shawly** [comment]
Sorry for the late reply! Thanks for noticing, I fixed it right now. The next release will have this change.
